services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: midterm
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: midterm
    ports:
      - "3307:3306"
    volumes:
      - ./createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
